language: ruby
rvm: 1.9.3
env:
  global:
    - secure: gUVSU/Eu2rRJ4WZzvlDPseTbCIV/Nv/xNkAeSyMSqsCcdbP57y22YrArQGYLJ7UB4lNlQDDCtQTaMtoE28GCHjPWBDsX22X2hTJQxhS0fTFN9aIpPea2dcCiKTnNIS2Jh9qmV23Ly3XuI0YvDLuIs3YK9E4NtH/msz6IiUUmN9w=

branches:
  except:
    - gh-pages

script: rake travis

after_success: ./update-gh-pages.sh
