# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "https://cdn.viosey.com/img/blog/favicon.ico"
    high_res_favicon: "https://cdn.viosey.com/img/blog/favicon-highres.png"
    apple_touch_icon: "https://cdn.viosey.com/img/blog/favicon-highres.png"
    keywords: "Viosey, viosey blog, blog"

# Jump Links Settings
url:
    rss: "/atom.xml"
    daily_pic: "#"
    logo: "https://viosey.com"


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "我怕永不再见，我也怕再次重逢。"
    theme_color: "#607D8B"
    theme_sub_color: "#90A4AE"
    hyperlink_color: "#607D8B"
    button_color: "#607D8B"
    android_chrome_color: "#607D8B"
    nprogress_color: "#000"
    nprogress_buffer: "200"
    
# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: false

# Reading experience
# markdown available value:
#     Material | Github | Plain
reading:
    markdown: Github
    entry_excerpt: 80
    code_highlight: solarized-white

# Thumbnail Settings
thumbnail:
    purecolor: 
    random_amount: 5

# Background Settings
# bing available parameter:
#     new | color= | type=
#         color available value: black, blue, brown, green, multi, orange, pink, purple, red, white, yellow
#         type available value: A (animal), C (culture), N (nature), S (space), T (travel)
background:
    purecolor: "#e9ebec"
    #bgimg: "/img/bg.png"
    bing: 
        enable: false
        parameter: 

# Image Settings
img:
    logo: "https://cdn.viosey.com/img/logo/viosey_logo-blue.png"
    avatar: "https://cdn.viosey.com/img/avatar/Natsume-blog-tiny.jpg"
    daily_pic: "https://cdn.viosey.com/img/blog/unsplash-man-face-mountain.jpg!blogtop"
    sidebar_header: "https://cdn.viosey.com/img/blog/snow_square.png"
    footerico: "/img/footer/footer_ico-"
    upyun_logo: "/img/upyun_logo.png"
    random_thumbnail: "/img/random/"

# Custom Fonts
fonts: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Menu
sns:
    email: "hiviosey@gmail.com"
    twitter: "https://twitter.com/viosey"
    facebook: "https://www.facebook.com/viosey"
    googleplus: 
    weibo: 
    instagram: 
    tumblr: 
    github: "https://github.com/viosey"
    
# Sidebar User Dropdown
dropdown: 
    viosey.com: 
        link: "https://viosey.com"
        icon: map
    email me:
        link: "mailto:hiviosey@gmail.com"
        icon: email

# Pages Menu
pages:
    映像: "/gallery/"
    关于我: "/about/"
    标签云: "/tags/"
    友情链接: "/links/"
    
    

# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------

# Comment Systems
# Available value:
#     duoshuo | disqus
comment:
    use: duoshuo
    shortname: viosey
    duoshuo_thread_key: id
    duoshuo_embed_js_url: "https://cdn.viosey.com/static/js/dsembed.js"
    
# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: local
    swiftype_key: 
    path: search.xml
    field: post

# Leancloud Views
leancloud:
    enable: true
    app_id: hhuSWbeGtVDeME8mtNXXzYp9-gzGzoHsz
    app_key: GeXInHwpP9i56MNX9U2lLci9
    av_core_mini: "https://cdn.viosey.com/static/js/av-core-mini-0.6.1.js"
    
# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://cdn.viosey.com/static/js/busuanzi.pure.mini.js"