# ---------------------------------------------------------------
# Site Information Settings
# ---------------------------------------------------------------

# Head info
head:
    favicon: "/img/favicon.png"
    high_res_favicon: "/img/favicon.png"
    apple_touch_icon: "/img/favicon.png"
    keywords: 

# Jump Links Settings
url:
    about: #"/about"
    rss: 
    daily_pic: "#"
    logo: 


# ---------------------------------------------------------------
# Style Settings
# ---------------------------------------------------------------

# Schemes
scheme: Paradox
#scheme: Isolation

# UI & UX: slogan, color, effect
uiux:
    slogan: "Hi, nice to meet you"
    theme_color: "#039BE5"
    theme_sub_color: "#00BCD4"
    hyperlink_color: "#039BE5"
    android_chrome_color: "#039BE5"
    nprogress_color: "#FF4081"
    nprogress_buffer: "800"
    
# JS Effect Switches
js_effect:
    fade: true
    smoothscroll: true
    fab_hover_in: false
    fab_hover_out: true

# Reading experience
# markdown available value:
#     Material | Github
reading:
    markdown: Github
    entry_excerpt: 80

# Thumbnail Settings
thumbnail:
    purecolor: 
    random_amount: 5

# Background Settings
background:
    purecolor: "#F5F5F5"
    bgimg: "/img/bg.png"

# Images Settings
img:
    logo: "/img/logo.png"
    avatar: "/img/avatar.png"
    daily_pic: "/img/daily_pic.png"
    sidebar_header: "/img/sidebar_header.png"
    footerico: "/img/footer/footer_ico-"
    #upyun_logo: "/img/upyun_logo.png"
    random_thumbnail: "/img/random/"

# Custom Fonts
fonts: Roboto, "Helvetica Neue", Helvetica, "PingFang SC", "Hiragino Sans GB", "Microsoft YaHei", "微软雅黑", Arial, sans-serif

# ---------------------------------------------------------------
# Menu Settings
# ---------------------------------------------------------------

# SNS Menu
sns:
    email: youremail@email.com
    twitter: "https://twitter.com/twitter"
    facebook: "https://www.facebook.com/facebook"
    googleplus: "https://www.google.com/"
    weibo: 
    instagram: 
    tumblr: 
    github: 

# Pages Menu
pages:
    


# ---------------------------------------------------------------
# Integrated Services
# ---------------------------------------------------------------
    
# Comment Systems
# Available value:
#     duoshuo | disqus
comment:
    use: 
    shortname: 
    duoshuo_embed_js_url: "https://static.duoshuo.com/embed.js"

# Search Systems
# Available value:
#     swiftype | google | local
search:
    use: google
    swiftype_key: 
        
# Leancloud Views
leancloud:
    enable: false
    app_id: #你的app_id
    app_key: #你的app_key
    av_core_mini: "https://cdn1.lncld.net/static/js/av-core-mini-0.6.1.js"
    
# Busuanzi 不蒜子 Views
busuanzi:
    enable: false
    all_site_uv: false
    post_pv: false
    busuanzi_pure_mini_js: "https://dn-lbstatics.qbox.me/busuanzi/2.3/busuanzi.pure.mini.js"